export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_USER = 'LOADING_USER';

// Notes types
export const SET_NOTE = 'SET_NOTE';
export const SET_FILTERED_NOTES = 'SET_FILTERED_NOTES';
export const SET_NOTE_ERRORS = 'SET_NOTE_ERRORS';
export const SET_NOTES = 'SET_NOTES';
export const MOVE_NOTE = 'MOVE_NOTE';
export const MOVE_NOTE_BACK = 'MOVE_NOTE_BACK';
export const MOVE_NOTE_CLEAR = 'MOVE_NOTE_CLEAR';
export const NOTES_LOADING = 'NOTES_LOADING';
export const NOTES_FETCHED = 'NOTES_FETCHED';
export const FETCH_NOTE = 'FETCH_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const CREATE_NOTE = 'CREATE_NOTE';
export const DELETE_NOTE_FOREVER = 'DELETE_NOTE_FOREVER';
export const CHANGE_NOTE_COLOR = 'CHANGE_NOTE_COLOR';
export const DELETE_NOTES_FOREVER = 'DELETE_NOTES_FOREVER';
export const STAR_NOTE = 'STAR_NOTE';
export const CHANGE_NOTE_LABELS = 'CHANGE_NOTE_LABELS';
export const DELETE_NOTE_FROM_STATE = 'DELETE_NOTE_FROM_STATE';
export const DELETE_NOTE_IMAGE = 'DELETE_NOTE_IMAGE';
export const LOADING_NOTE_IMAGE = 'LOADING_NOTE_IMAGE';
export const LOADING_NOTE_IMAGE_FINISH = 'LOADING_NOTE_IMAGE_FINISH';

// Labels types
export const FETCH_LABELS = 'FETCH_LABELS';
export const CREATE_LABEL = 'CREATE_LABEL';
export const EDIT_LABEL_NAME = 'EDIT_LABEL_NAME';
export const ADD_NOTE_TO_LABEL = 'ADD_NOTE_TO_LABEL';
export const OPEN_EDIT_LABELS = 'OPEN_EDIT_LABELS';
export const CLOSE_EDIT_LABELS = 'CLOSE_EDIT_LABELS';
export const DELETE_LABEL = 'DELETE_LABEL';

// UI types
export const FETCH_USER_UI = 'FETCH_USER_UI';
export const FETCH_THEME = 'FETCH_THEME';
export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_COLORS = 'SET_COLORS';
export const FETCH_VIEW = 'FETCH_VIEW';
export const CHANGE_VIEW = 'CHANGE_VIEW';
